# backend/catalog.py

CATALOG = {
    "eng_water_capacity": {
        "dataset_id": "eng_water_capacity",
        "department": "engineering",
        "name": "Water Main Capacity by Zone",
        "description": "Water infrastructure utilization and condition scores by anonymized zone",
        "sensitivity": "internal",
        "fields": ["zone_id", "asset_type", "capacity_pct", "condition_score", "upgrade_year"],
        "allowed_roles": ["engineer", "planner", "analyst", "admin"],
        "integration_key": "zone_id",
        "tags": ["infrastructure", "water", "capacity", "growth-planning"],
        "steward": "engineering@regionofwaterloo.ca",
        "last_updated": "2024-03-15",
        "record_count": 6,
    },
    "pln_permits": {
        "dataset_id": "pln_permits",
        "department": "planning",
        "name": "Development Permits by Zone",
        "description": "Active and approved permits, zoning class, unit counts by zone",
        "sensitivity": "public",
        "fields": ["zone_id", "permit_type", "zoning_class", "unit_count", "status", "density_approved"],
        "allowed_roles": ["engineer", "planner", "health", "analyst", "admin"],
        "integration_key": "zone_id",
        "tags": ["permits", "zoning", "density", "development", "housing", "infill"],
        "steward": "planning@regionofwaterloo.ca",
        "last_updated": "2024-03-15",
        "record_count": 6,
    },
    "hlt_zone_health": {
        "dataset_id": "hlt_zone_health",
        "department": "health",
        "name": "Zone Health Indicators",
        "description": "Aggregated health infrastructure capacity and population vulnerability by zone",
        "sensitivity": "confidential",
        "fields": ["zone_id", "er_utilization_pct", "clinic_count", "vulnerability_index", "gp_ratio"],
        "allowed_roles": ["health", "admin"],
        "integration_key": "zone_id",
        "tags": ["health", "er", "capacity", "vulnerability", "clinics"],
        "steward": "publichealth@regionofwaterloo.ca",
        "last_updated": "2024-03-15",
        "record_count": 6,
    },
    "trt_routes": {
        "dataset_id": "trt_routes",
        "department": "transit",
        "name": "Transit Routes and Ridership",
        "description": "Route frequency, average ridership, and service level by zone",
        "sensitivity": "public",
        "fields": ["zone_id", "route_id", "corridor", "frequency_min", "avg_ridership", "service_level"],
        "allowed_roles": ["engineer", "planner", "health", "analyst", "admin"],
        "integration_key": "zone_id",
        "tags": ["transit", "routes", "ridership", "frequency", "corridor", "grt"],
        "steward": "grt@regionofwaterloo.ca",
        "last_updated": "2024-03-15",
        "record_count": 6,
    },
}
